version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: ./dev/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/go/build
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ADDR: mysql:3306
      MYSQL_DATABASE: dena-hack
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ADDR: db:3306
      MYSQL_DATABASE: dena-hack
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  db_data:
